Add basic typescript support
diogomoretti/javali pull request #1
Opened 2019-03-28 19:16 UTC by eloiqs

Hey there!

Typescript is awesome for third party libraries. Lets encourage its use!

This is a basic prototype, I didn't put much thought into it and just wanted to get something basic going so others can improve on top.

Feel free to use it as you want! 😄 

example usage:
```
javali my-ts-lib --ts
```

2019-03-28 19:49 UTC, diogomoretti commented
Thanks for your PR @eloiqs 😉 Could you put the instructions in readme file?

2019-03-29 19:53 UTC, eloiqs commented
I added a mention and example in the readme!

I also improved the implementation a bit. Let me know what you think! 😄

2019-04-01 11:44 UTC, diogomoretti requested changes

2019-04-01 11:44 UTC, diogomoretti commented on cli/index.js
> +  .option('--typescript', 'use typescript')
Add `-t` short param

2019-04-01 13:58 UTC, diogomoretti approved these changes

2019-04-01 16:45 UTC, merged

2019-04-01 16:50 UTC, diogomoretti commented
[Javali@1.1.0 was released](https://www.npmjs.com/package/javali/v/1.1.0). Thanks!